baseURL = 'https://capable-starship-1b455b.netlify.app/'
languageCode = 'en-us'
title = 'Vinoo'

paginate = 5

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  author = "authors"
  category = "categories"